package org.alex.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:39:44.882+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndpointAssignmentServiceService",
                  wsdlLocation = "http://localhost:888/assignment?wsdl",
                  targetNamespace = "http://endpoint.alex.org/")
public class EndpointAssignmentServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.alex.org/", "EndpointAssignmentServiceService");
    public final static QName EndpointAssignmentServicePort = new QName("http://endpoint.alex.org/", "EndpointAssignmentServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:888/assignment?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndpointAssignmentServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:888/assignment?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndpointAssignmentServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndpointAssignmentServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointAssignmentServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndpointAssignmentServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndpointAssignmentServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndpointAssignmentServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndpointAssignmentService
     */
    @WebEndpoint(name = "EndpointAssignmentServicePort")
    public EndpointAssignmentService getEndpointAssignmentServicePort() {
        return super.getPort(EndpointAssignmentServicePort, EndpointAssignmentService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointAssignmentService
     */
    @WebEndpoint(name = "EndpointAssignmentServicePort")
    public EndpointAssignmentService getEndpointAssignmentServicePort(WebServiceFeature... features) {
        return super.getPort(EndpointAssignmentServicePort, EndpointAssignmentService.class, features);
    }

}
