package org.alex.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:39:45.308+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndpointAssigneeServiceService",
                  wsdlLocation = "http://localhost:888/assignee?wsdl",
                  targetNamespace = "http://endpoint.alex.org/")
public class EndpointAssigneeServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.alex.org/", "EndpointAssigneeServiceService");
    public final static QName EndpointAssigneeServicePort = new QName("http://endpoint.alex.org/", "EndpointAssigneeServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:888/assignee?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndpointAssigneeServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:888/assignee?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndpointAssigneeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndpointAssigneeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointAssigneeServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndpointAssigneeServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndpointAssigneeServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndpointAssigneeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndpointAssigneeService
     */
    @WebEndpoint(name = "EndpointAssigneeServicePort")
    public EndpointAssigneeService getEndpointAssigneeServicePort() {
        return super.getPort(EndpointAssigneeServicePort, EndpointAssigneeService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointAssigneeService
     */
    @WebEndpoint(name = "EndpointAssigneeServicePort")
    public EndpointAssigneeService getEndpointAssigneeServicePort(WebServiceFeature... features) {
        return super.getPort(EndpointAssigneeServicePort, EndpointAssigneeService.class, features);
    }

}
