package org.alex.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:45.282+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.alex.org/", name = "EndpointTask")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointTask {

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTask/getTaskRequest", output = "http://endpoint.alex.org/EndpointTask/getTaskResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointTask/getTask/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "getTask", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetTask")
    @ResponseWrapper(localName = "getTaskResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.alex.endpoint.Task getTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalArgumentException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTask/getAllTaskRequest", output = "http://endpoint.alex.org/EndpointTask/getAllTaskResponse")
    @RequestWrapper(localName = "getAllTask", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAllTask")
    @ResponseWrapper(localName = "getAllTaskResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAllTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.alex.endpoint.Task> getAllTask();

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTask/createTaskRequest", output = "http://endpoint.alex.org/EndpointTask/createTaskResponse")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.CreateTaskResponse")
    public void createTask(
        @WebParam(name = "arg0", targetNamespace = "")
        org.alex.endpoint.Task arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTask/deleteTaskRequest", output = "http://endpoint.alex.org/EndpointTask/deleteTaskResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointTask/deleteTask/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "deleteTask", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.DeleteTask")
    @ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.DeleteTaskResponse")
    public void deleteTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalArgumentException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTask/updateTaskRequest", output = "http://endpoint.alex.org/EndpointTask/updateTaskResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointTask/updateTask/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "updateTask", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.UpdateTask")
    @ResponseWrapper(localName = "updateTaskResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.UpdateTaskResponse")
    public void updateTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        org.alex.endpoint.Task arg1
    ) throws IllegalArgumentException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTask/mergeTaskRequest", output = "http://endpoint.alex.org/EndpointTask/mergeTaskResponse")
    @RequestWrapper(localName = "mergeTask", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.MergeTask")
    @ResponseWrapper(localName = "mergeTaskResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.MergeTaskResponse")
    public void mergeTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<org.alex.endpoint.Task> arg0
    );
}
