package org.alex.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:39:45.786+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndpointTaskServiceService",
                  wsdlLocation = "http://localhost:888/task?wsdl",
                  targetNamespace = "http://endpoint.alex.org/")
public class EndpointTaskServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.alex.org/", "EndpointTaskServiceService");
    public final static QName EndpointTaskServicePort = new QName("http://endpoint.alex.org/", "EndpointTaskServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:888/task?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndpointTaskServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:888/task?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndpointTaskServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndpointTaskServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointTaskServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndpointTaskServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndpointTaskServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndpointTaskServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndpointTaskService
     */
    @WebEndpoint(name = "EndpointTaskServicePort")
    public EndpointTaskService getEndpointTaskServicePort() {
        return super.getPort(EndpointTaskServicePort, EndpointTaskService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointTaskService
     */
    @WebEndpoint(name = "EndpointTaskServicePort")
    public EndpointTaskService getEndpointTaskServicePort(WebServiceFeature... features) {
        return super.getPort(EndpointTaskServicePort, EndpointTaskService.class, features);
    }

}
