package org.alex.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:45.988+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndpointAuthorizationService",
                  wsdlLocation = "http://localhost:888/auth?wsdl",
                  targetNamespace = "http://endpoint.alex.org/")
public class EndpointAuthorizationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.alex.org/", "EndpointAuthorizationService");
    public final static QName EndpointAuthorizationPort = new QName("http://endpoint.alex.org/", "EndpointAuthorizationPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:888/auth?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndpointAuthorizationService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:888/auth?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndpointAuthorizationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndpointAuthorizationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointAuthorizationService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndpointAuthorizationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndpointAuthorizationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndpointAuthorizationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndpointAuthorization
     */
    @WebEndpoint(name = "EndpointAuthorizationPort")
    public EndpointAuthorization getEndpointAuthorizationPort() {
        return super.getPort(EndpointAuthorizationPort, EndpointAuthorization.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointAuthorization
     */
    @WebEndpoint(name = "EndpointAuthorizationPort")
    public EndpointAuthorization getEndpointAuthorizationPort(WebServiceFeature... features) {
        return super.getPort(EndpointAuthorizationPort, EndpointAuthorization.class, features);
    }

}
