package org.alex.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:44.397+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndpointAssignmentService",
                  wsdlLocation = "http://localhost:888/assignment?wsdl",
                  targetNamespace = "http://endpoint.alex.org/")
public class EndpointAssignmentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.alex.org/", "EndpointAssignmentService");
    public final static QName EndpointAssignmentPort = new QName("http://endpoint.alex.org/", "EndpointAssignmentPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:888/assignment?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndpointAssignmentService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:888/assignment?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndpointAssignmentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndpointAssignmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointAssignmentService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndpointAssignmentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndpointAssignmentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndpointAssignmentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndpointAssignment
     */
    @WebEndpoint(name = "EndpointAssignmentPort")
    public EndpointAssignment getEndpointAssignmentPort() {
        return super.getPort(EndpointAssignmentPort, EndpointAssignment.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointAssignment
     */
    @WebEndpoint(name = "EndpointAssignmentPort")
    public EndpointAssignment getEndpointAssignmentPort(WebServiceFeature... features) {
        return super.getPort(EndpointAssignmentPort, EndpointAssignment.class, features);
    }

}
