package org.alex.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:44.880+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.alex.org/", name = "EndpointAssignee")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointAssignee {

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssignee/createAssigneeRequest", output = "http://endpoint.alex.org/EndpointAssignee/createAssigneeResponse")
    @RequestWrapper(localName = "createAssignee", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.CreateAssignee")
    @ResponseWrapper(localName = "createAssigneeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.CreateAssigneeResponse")
    public void createAssignee(
        @WebParam(name = "arg0", targetNamespace = "")
        org.alex.endpoint.Assignee arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssignee/getAssigneeRequest", output = "http://endpoint.alex.org/EndpointAssignee/getAssigneeResponse", fault = {@FaultAction(className = IllegalStringException_Exception.class, value = "http://endpoint.alex.org/EndpointAssignee/getAssignee/Fault/IllegalStringException")})
    @RequestWrapper(localName = "getAssignee", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAssignee")
    @ResponseWrapper(localName = "getAssigneeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAssigneeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.alex.endpoint.Assignee getAssignee(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalStringException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssignee/deleteAssigneeRequest", output = "http://endpoint.alex.org/EndpointAssignee/deleteAssigneeResponse", fault = {@FaultAction(className = IllegalStringException_Exception.class, value = "http://endpoint.alex.org/EndpointAssignee/deleteAssignee/Fault/IllegalStringException")})
    @RequestWrapper(localName = "deleteAssignee", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.DeleteAssignee")
    @ResponseWrapper(localName = "deleteAssigneeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.DeleteAssigneeResponse")
    public void deleteAssignee(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalStringException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssignee/getAssigneeByLoginRequest", output = "http://endpoint.alex.org/EndpointAssignee/getAssigneeByLoginResponse")
    @RequestWrapper(localName = "getAssigneeByLogin", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAssigneeByLogin")
    @ResponseWrapper(localName = "getAssigneeByLoginResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAssigneeByLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.alex.endpoint.Assignee getAssigneeByLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssignee/getAllAssigneeRequest", output = "http://endpoint.alex.org/EndpointAssignee/getAllAssigneeResponse")
    @RequestWrapper(localName = "getAllAssignee", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAllAssignee")
    @ResponseWrapper(localName = "getAllAssigneeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAllAssigneeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.alex.endpoint.Assignee> getAllAssignee();

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssignee/getAdminGroupRequest", output = "http://endpoint.alex.org/EndpointAssignee/getAdminGroupResponse")
    @RequestWrapper(localName = "getAdminGroup", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAdminGroup")
    @ResponseWrapper(localName = "getAdminGroupResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAdminGroupResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAdminGroup();

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssignee/mergeAssigneeRequest", output = "http://endpoint.alex.org/EndpointAssignee/mergeAssigneeResponse")
    @RequestWrapper(localName = "mergeAssignee", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.MergeAssignee")
    @ResponseWrapper(localName = "mergeAssigneeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.MergeAssigneeResponse")
    public void mergeAssignee(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<org.alex.endpoint.Assignee> arg0
    );
}
