package org.alex.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:39:45.768+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.alex.org/", name = "EndpointTaskService")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointTaskService {

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTaskService/createRequest", output = "http://endpoint.alex.org/EndpointTaskService/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        org.alex.endpoint.Task arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTaskService/deleteRequest", output = "http://endpoint.alex.org/EndpointTaskService/deleteResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointTaskService/delete/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "delete", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalArgumentException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTaskService/updateTaskRequest", output = "http://endpoint.alex.org/EndpointTaskService/updateTaskResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointTaskService/updateTask/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "updateTask", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.UpdateTask")
    @ResponseWrapper(localName = "updateTaskResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.UpdateTaskResponse")
    public void updateTask(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        org.alex.endpoint.Task arg1
    ) throws IllegalArgumentException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTaskService/getAllRequest", output = "http://endpoint.alex.org/EndpointTaskService/getAllResponse")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.alex.endpoint.Task> getAll();

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTaskService/getRequest", output = "http://endpoint.alex.org/EndpointTaskService/getResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointTaskService/get/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "get", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.alex.endpoint.Task get(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalArgumentException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointTaskService/mergeRequest", output = "http://endpoint.alex.org/EndpointTaskService/mergeResponse")
    @RequestWrapper(localName = "merge", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.MergeResponse")
    public void merge(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<org.alex.endpoint.Task> arg0
    );
}
