package org.alex.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:39:45.291+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.alex.org/", name = "EndpointAssigneeService")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointAssigneeService {

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssigneeService/createRequest", output = "http://endpoint.alex.org/EndpointAssigneeService/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        org.alex.endpoint.Task arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssigneeService/deleteRequest", output = "http://endpoint.alex.org/EndpointAssigneeService/deleteResponse")
    @RequestWrapper(localName = "delete", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssigneeService/getAllRequest", output = "http://endpoint.alex.org/EndpointAssigneeService/getAllResponse")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.alex.endpoint.Task> getAll();

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssigneeService/getAdminGroupRequest", output = "http://endpoint.alex.org/EndpointAssigneeService/getAdminGroupResponse")
    @RequestWrapper(localName = "getAdminGroup", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAdminGroup")
    @ResponseWrapper(localName = "getAdminGroupResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAdminGroupResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAdminGroup();

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssigneeService/getRequest", output = "http://endpoint.alex.org/EndpointAssigneeService/getResponse")
    @RequestWrapper(localName = "get", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.alex.endpoint.Task get(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointAssigneeService/mergeRequest", output = "http://endpoint.alex.org/EndpointAssigneeService/mergeResponse")
    @RequestWrapper(localName = "merge", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.MergeResponse")
    public void merge(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<org.alex.endpoint.Task> arg0
    );
}
