package org.alex.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:44.896+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EndpointAssigneeService",
                  wsdlLocation = "http://localhost:888/assignee?wsdl",
                  targetNamespace = "http://endpoint.alex.org/")
public class EndpointAssigneeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.alex.org/", "EndpointAssigneeService");
    public final static QName EndpointAssigneePort = new QName("http://endpoint.alex.org/", "EndpointAssigneePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:888/assignee?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EndpointAssigneeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:888/assignee?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EndpointAssigneeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EndpointAssigneeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointAssigneeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EndpointAssigneeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EndpointAssigneeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EndpointAssigneeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EndpointAssignee
     */
    @WebEndpoint(name = "EndpointAssigneePort")
    public EndpointAssignee getEndpointAssigneePort() {
        return super.getPort(EndpointAssigneePort, EndpointAssignee.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointAssignee
     */
    @WebEndpoint(name = "EndpointAssigneePort")
    public EndpointAssignee getEndpointAssigneePort(WebServiceFeature... features) {
        return super.getPort(EndpointAssigneePort, EndpointAssignee.class, features);
    }

}
