package org.alex.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-18T12:39:46.122+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.alex.org/", name = "EndpointProjectService")
@XmlSeeAlso({ObjectFactory.class})
public interface EndpointProjectService {

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointProjectService/getAllRequest", output = "http://endpoint.alex.org/EndpointProjectService/getAllResponse")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.alex.endpoint.Task> getAll();

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointProjectService/createRequest", output = "http://endpoint.alex.org/EndpointProjectService/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        org.alex.endpoint.Task arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointProjectService/getRequest", output = "http://endpoint.alex.org/EndpointProjectService/getResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointProjectService/get/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "get", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.GetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.alex.endpoint.Task get(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalArgumentException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointProjectService/mergeRequest", output = "http://endpoint.alex.org/EndpointProjectService/mergeResponse")
    @RequestWrapper(localName = "merge", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.MergeResponse")
    public void merge(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<org.alex.endpoint.Task> arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.alex.org/EndpointProjectService/deleteRequest", output = "http://endpoint.alex.org/EndpointProjectService/deleteResponse", fault = {@FaultAction(className = IllegalArgumentException_Exception.class, value = "http://endpoint.alex.org/EndpointProjectService/delete/Fault/IllegalArgumentException")})
    @RequestWrapper(localName = "delete", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://endpoint.alex.org/", className = "org.alex.endpoint.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws IllegalArgumentException_Exception;
}
