
package org.alex.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:45.966+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "GeneralSecurityException", targetNamespace = "http://endpoint.alex.org/")
public class GeneralSecurityException_Exception extends Exception {

    private org.alex.endpoint.GeneralSecurityException generalSecurityException;

    public GeneralSecurityException_Exception() {
        super();
    }

    public GeneralSecurityException_Exception(String message) {
        super(message);
    }

    public GeneralSecurityException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GeneralSecurityException_Exception(String message, org.alex.endpoint.GeneralSecurityException generalSecurityException) {
        super(message);
        this.generalSecurityException = generalSecurityException;
    }

    public GeneralSecurityException_Exception(String message, org.alex.endpoint.GeneralSecurityException generalSecurityException, java.lang.Throwable cause) {
        super(message, cause);
        this.generalSecurityException = generalSecurityException;
    }

    public org.alex.endpoint.GeneralSecurityException getFaultInfo() {
        return this.generalSecurityException;
    }
}
