
package org.alex.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:45.632+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "IllegalStringException", targetNamespace = "http://endpoint.alex.org/")
public class IllegalStringException_Exception extends Exception {

    private org.alex.endpoint.IllegalStringException illegalStringException;

    public IllegalStringException_Exception() {
        super();
    }

    public IllegalStringException_Exception(String message) {
        super(message);
    }

    public IllegalStringException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IllegalStringException_Exception(String message, org.alex.endpoint.IllegalStringException illegalStringException) {
        super(message);
        this.illegalStringException = illegalStringException;
    }

    public IllegalStringException_Exception(String message, org.alex.endpoint.IllegalStringException illegalStringException, java.lang.Throwable cause) {
        super(message, cause);
        this.illegalStringException = illegalStringException;
    }

    public org.alex.endpoint.IllegalStringException getFaultInfo() {
        return this.illegalStringException;
    }
}
