
package org.alex.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-22T14:39:45.958+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "UnsupportedEncodingException", targetNamespace = "http://endpoint.alex.org/")
public class UnsupportedEncodingException_Exception extends Exception {

    private org.alex.endpoint.UnsupportedEncodingException unsupportedEncodingException;

    public UnsupportedEncodingException_Exception() {
        super();
    }

    public UnsupportedEncodingException_Exception(String message) {
        super(message);
    }

    public UnsupportedEncodingException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UnsupportedEncodingException_Exception(String message, org.alex.endpoint.UnsupportedEncodingException unsupportedEncodingException) {
        super(message);
        this.unsupportedEncodingException = unsupportedEncodingException;
    }

    public UnsupportedEncodingException_Exception(String message, org.alex.endpoint.UnsupportedEncodingException unsupportedEncodingException, java.lang.Throwable cause) {
        super(message, cause);
        this.unsupportedEncodingException = unsupportedEncodingException;
    }

    public org.alex.endpoint.UnsupportedEncodingException getFaultInfo() {
        return this.unsupportedEncodingException;
    }
}
